#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2503.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SQL_2503_Fashion")]
	public partial class dbSQL_2503DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCUSTOMER(CUSTOMER instance);
    partial void UpdateCUSTOMER(CUSTOMER instance);
    partial void DeleteCUSTOMER(CUSTOMER instance);
    partial void InsertPRODUCT(PRODUCT instance);
    partial void UpdatePRODUCT(PRODUCT instance);
    partial void DeletePRODUCT(PRODUCT instance);
    partial void InsertORDER_DETAIL(ORDER_DETAIL instance);
    partial void UpdateORDER_DETAIL(ORDER_DETAIL instance);
    partial void DeleteORDER_DETAIL(ORDER_DETAIL instance);
    partial void InsertCATEGORy(CATEGORy instance);
    partial void UpdateCATEGORy(CATEGORy instance);
    partial void DeleteCATEGORy(CATEGORy instance);
    partial void InsertADMIN(ADMIN instance);
    partial void UpdateADMIN(ADMIN instance);
    partial void DeleteADMIN(ADMIN instance);
    partial void InsertORDER(ORDER instance);
    partial void UpdateORDER(ORDER instance);
    partial void DeleteORDER(ORDER instance);
    #endregion
		
		public dbSQL_2503DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SQL_2503_FashionConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbSQL_2503DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbSQL_2503DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbSQL_2503DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbSQL_2503DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CUSTOMER> CUSTOMERs
		{
			get
			{
				return this.GetTable<CUSTOMER>();
			}
		}
		
		public System.Data.Linq.Table<PRODUCT> PRODUCTs
		{
			get
			{
				return this.GetTable<PRODUCT>();
			}
		}
		
		public System.Data.Linq.Table<ORDER_DETAIL> ORDER_DETAILs
		{
			get
			{
				return this.GetTable<ORDER_DETAIL>();
			}
		}
		
		public System.Data.Linq.Table<CATEGORy> CATEGORies
		{
			get
			{
				return this.GetTable<CATEGORy>();
			}
		}
		
		public System.Data.Linq.Table<ADMIN> ADMINs
		{
			get
			{
				return this.GetTable<ADMIN>();
			}
		}
		
		public System.Data.Linq.Table<ORDER> ORDERs
		{
			get
			{
				return this.GetTable<ORDER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CUSTOMER")]
	public partial class CUSTOMER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_CUS;
		
		private string _NAME;
		
		private string _UN;
		
		private string _PW;
		
		private string _EMAIL;
		
		private string _ADDRESS;
		
		private string _PHONENUMBER;
		
		private System.Nullable<System.DateTime> _DATEOFBIRTH;
		
		private EntitySet<ORDER> _ORDERs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CUSChanging(int value);
    partial void OnID_CUSChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnUNChanging(string value);
    partial void OnUNChanged();
    partial void OnPWChanging(string value);
    partial void OnPWChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnADDRESSChanging(string value);
    partial void OnADDRESSChanged();
    partial void OnPHONENUMBERChanging(string value);
    partial void OnPHONENUMBERChanged();
    partial void OnDATEOFBIRTHChanging(System.Nullable<System.DateTime> value);
    partial void OnDATEOFBIRTHChanged();
    #endregion
		
		public CUSTOMER()
		{
			this._ORDERs = new EntitySet<ORDER>(new Action<ORDER>(this.attach_ORDERs), new Action<ORDER>(this.detach_ORDERs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CUS", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_CUS
		{
			get
			{
				return this._ID_CUS;
			}
			set
			{
				if ((this._ID_CUS != value))
				{
					this.OnID_CUSChanging(value);
					this.SendPropertyChanging();
					this._ID_CUS = value;
					this.SendPropertyChanged("ID_CUS");
					this.OnID_CUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UN", DbType="VarChar(50)")]
		public string UN
		{
			get
			{
				return this._UN;
			}
			set
			{
				if ((this._UN != value))
				{
					this.OnUNChanging(value);
					this.SendPropertyChanging();
					this._UN = value;
					this.SendPropertyChanged("UN");
					this.OnUNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PW", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string PW
		{
			get
			{
				return this._PW;
			}
			set
			{
				if ((this._PW != value))
				{
					this.OnPWChanging(value);
					this.SendPropertyChanging();
					this._PW = value;
					this.SendPropertyChanged("PW");
					this.OnPWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS", DbType="NVarChar(200)")]
		public string ADDRESS
		{
			get
			{
				return this._ADDRESS;
			}
			set
			{
				if ((this._ADDRESS != value))
				{
					this.OnADDRESSChanging(value);
					this.SendPropertyChanging();
					this._ADDRESS = value;
					this.SendPropertyChanged("ADDRESS");
					this.OnADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONENUMBER", DbType="VarChar(10)")]
		public string PHONENUMBER
		{
			get
			{
				return this._PHONENUMBER;
			}
			set
			{
				if ((this._PHONENUMBER != value))
				{
					this.OnPHONENUMBERChanging(value);
					this.SendPropertyChanging();
					this._PHONENUMBER = value;
					this.SendPropertyChanged("PHONENUMBER");
					this.OnPHONENUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATEOFBIRTH", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATEOFBIRTH
		{
			get
			{
				return this._DATEOFBIRTH;
			}
			set
			{
				if ((this._DATEOFBIRTH != value))
				{
					this.OnDATEOFBIRTHChanging(value);
					this.SendPropertyChanging();
					this._DATEOFBIRTH = value;
					this.SendPropertyChanged("DATEOFBIRTH");
					this.OnDATEOFBIRTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CUSTOMER_ORDER", Storage="_ORDERs", ThisKey="ID_CUS", OtherKey="ID_CUS")]
		public EntitySet<ORDER> ORDERs
		{
			get
			{
				return this._ORDERs;
			}
			set
			{
				this._ORDERs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ORDERs(ORDER entity)
		{
			this.SendPropertyChanging();
			entity.CUSTOMER = this;
		}
		
		private void detach_ORDERs(ORDER entity)
		{
			this.SendPropertyChanging();
			entity.CUSTOMER = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PRODUCT")]
	public partial class PRODUCT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_PRO;
		
		private string _NAME;
		
		private System.Nullable<decimal> _PRICE;
		
		private string _SIZE;
		
		private string _DESCRIPTION;
		
		private string _IMAGE;
		
		private System.Nullable<System.DateTime> _DATEUPDATE;
		
		private System.Nullable<int> _QUANTITIES;
		
		private System.Nullable<int> _ID_CAT;
		
		private EntitySet<ORDER_DETAIL> _ORDER_DETAILs;
		
		private EntityRef<CATEGORy> _CATEGORy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PROChanging(int value);
    partial void OnID_PROChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnPRICEChanging(System.Nullable<decimal> value);
    partial void OnPRICEChanged();
    partial void OnSIZEChanging(string value);
    partial void OnSIZEChanged();
    partial void OnDESCRIPTIONChanging(string value);
    partial void OnDESCRIPTIONChanged();
    partial void OnIMAGEChanging(string value);
    partial void OnIMAGEChanged();
    partial void OnDATEUPDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDATEUPDATEChanged();
    partial void OnQUANTITIESChanging(System.Nullable<int> value);
    partial void OnQUANTITIESChanged();
    partial void OnID_CATChanging(System.Nullable<int> value);
    partial void OnID_CATChanged();
    #endregion
		
		public PRODUCT()
		{
			this._ORDER_DETAILs = new EntitySet<ORDER_DETAIL>(new Action<ORDER_DETAIL>(this.attach_ORDER_DETAILs), new Action<ORDER_DETAIL>(this.detach_ORDER_DETAILs));
			this._CATEGORy = default(EntityRef<CATEGORy>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_PRO
		{
			get
			{
				return this._ID_PRO;
			}
			set
			{
				if ((this._ID_PRO != value))
				{
					this.OnID_PROChanging(value);
					this.SendPropertyChanging();
					this._ID_PRO = value;
					this.SendPropertyChanged("ID_PRO");
					this.OnID_PROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRICE", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> PRICE
		{
			get
			{
				return this._PRICE;
			}
			set
			{
				if ((this._PRICE != value))
				{
					this.OnPRICEChanging(value);
					this.SendPropertyChanging();
					this._PRICE = value;
					this.SendPropertyChanged("PRICE");
					this.OnPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SIZE", DbType="VarChar(10)")]
		public string SIZE
		{
			get
			{
				return this._SIZE;
			}
			set
			{
				if ((this._SIZE != value))
				{
					this.OnSIZEChanging(value);
					this.SendPropertyChanging();
					this._SIZE = value;
					this.SendPropertyChanged("SIZE");
					this.OnSIZEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPTION", DbType="NVarChar(MAX)")]
		public string DESCRIPTION
		{
			get
			{
				return this._DESCRIPTION;
			}
			set
			{
				if ((this._DESCRIPTION != value))
				{
					this.OnDESCRIPTIONChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPTION = value;
					this.SendPropertyChanged("DESCRIPTION");
					this.OnDESCRIPTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMAGE", DbType="VarChar(50)")]
		public string IMAGE
		{
			get
			{
				return this._IMAGE;
			}
			set
			{
				if ((this._IMAGE != value))
				{
					this.OnIMAGEChanging(value);
					this.SendPropertyChanging();
					this._IMAGE = value;
					this.SendPropertyChanged("IMAGE");
					this.OnIMAGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATEUPDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATEUPDATE
		{
			get
			{
				return this._DATEUPDATE;
			}
			set
			{
				if ((this._DATEUPDATE != value))
				{
					this.OnDATEUPDATEChanging(value);
					this.SendPropertyChanging();
					this._DATEUPDATE = value;
					this.SendPropertyChanged("DATEUPDATE");
					this.OnDATEUPDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITIES", DbType="Int")]
		public System.Nullable<int> QUANTITIES
		{
			get
			{
				return this._QUANTITIES;
			}
			set
			{
				if ((this._QUANTITIES != value))
				{
					this.OnQUANTITIESChanging(value);
					this.SendPropertyChanging();
					this._QUANTITIES = value;
					this.SendPropertyChanged("QUANTITIES");
					this.OnQUANTITIESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CAT", DbType="Int")]
		public System.Nullable<int> ID_CAT
		{
			get
			{
				return this._ID_CAT;
			}
			set
			{
				if ((this._ID_CAT != value))
				{
					if (this._CATEGORy.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_CATChanging(value);
					this.SendPropertyChanging();
					this._ID_CAT = value;
					this.SendPropertyChanged("ID_CAT");
					this.OnID_CATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PRODUCT_ORDER_DETAIL", Storage="_ORDER_DETAILs", ThisKey="ID_PRO", OtherKey="ID_PRO")]
		public EntitySet<ORDER_DETAIL> ORDER_DETAILs
		{
			get
			{
				return this._ORDER_DETAILs;
			}
			set
			{
				this._ORDER_DETAILs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CATEGORy_PRODUCT", Storage="_CATEGORy", ThisKey="ID_CAT", OtherKey="ID_CAT", IsForeignKey=true)]
		public CATEGORy CATEGORy
		{
			get
			{
				return this._CATEGORy.Entity;
			}
			set
			{
				CATEGORy previousValue = this._CATEGORy.Entity;
				if (((previousValue != value) 
							|| (this._CATEGORy.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CATEGORy.Entity = null;
						previousValue.PRODUCTs.Remove(this);
					}
					this._CATEGORy.Entity = value;
					if ((value != null))
					{
						value.PRODUCTs.Add(this);
						this._ID_CAT = value.ID_CAT;
					}
					else
					{
						this._ID_CAT = default(Nullable<int>);
					}
					this.SendPropertyChanged("CATEGORy");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ORDER_DETAILs(ORDER_DETAIL entity)
		{
			this.SendPropertyChanging();
			entity.PRODUCT = this;
		}
		
		private void detach_ORDER_DETAILs(ORDER_DETAIL entity)
		{
			this.SendPropertyChanging();
			entity.PRODUCT = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ORDER_DETAIL")]
	public partial class ORDER_DETAIL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_ORD;
		
		private int _ID_PRO;
		
		private System.Nullable<int> _QUANTITY;
		
		private System.Nullable<decimal> _UNITPRICE;
		
		private EntityRef<PRODUCT> _PRODUCT;
		
		private EntityRef<ORDER> _ORDER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ORDChanging(int value);
    partial void OnID_ORDChanged();
    partial void OnID_PROChanging(int value);
    partial void OnID_PROChanged();
    partial void OnQUANTITYChanging(System.Nullable<int> value);
    partial void OnQUANTITYChanged();
    partial void OnUNITPRICEChanging(System.Nullable<decimal> value);
    partial void OnUNITPRICEChanged();
    #endregion
		
		public ORDER_DETAIL()
		{
			this._PRODUCT = default(EntityRef<PRODUCT>);
			this._ORDER = default(EntityRef<ORDER>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ORD", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_ORD
		{
			get
			{
				return this._ID_ORD;
			}
			set
			{
				if ((this._ID_ORD != value))
				{
					if (this._ORDER.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ORDChanging(value);
					this.SendPropertyChanging();
					this._ID_ORD = value;
					this.SendPropertyChanged("ID_ORD");
					this.OnID_ORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_PRO
		{
			get
			{
				return this._ID_PRO;
			}
			set
			{
				if ((this._ID_PRO != value))
				{
					if (this._PRODUCT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_PROChanging(value);
					this.SendPropertyChanging();
					this._ID_PRO = value;
					this.SendPropertyChanged("ID_PRO");
					this.OnID_PROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY", DbType="Int")]
		public System.Nullable<int> QUANTITY
		{
			get
			{
				return this._QUANTITY;
			}
			set
			{
				if ((this._QUANTITY != value))
				{
					this.OnQUANTITYChanging(value);
					this.SendPropertyChanging();
					this._QUANTITY = value;
					this.SendPropertyChanged("QUANTITY");
					this.OnQUANTITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNITPRICE", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UNITPRICE
		{
			get
			{
				return this._UNITPRICE;
			}
			set
			{
				if ((this._UNITPRICE != value))
				{
					this.OnUNITPRICEChanging(value);
					this.SendPropertyChanging();
					this._UNITPRICE = value;
					this.SendPropertyChanged("UNITPRICE");
					this.OnUNITPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PRODUCT_ORDER_DETAIL", Storage="_PRODUCT", ThisKey="ID_PRO", OtherKey="ID_PRO", IsForeignKey=true)]
		public PRODUCT PRODUCT
		{
			get
			{
				return this._PRODUCT.Entity;
			}
			set
			{
				PRODUCT previousValue = this._PRODUCT.Entity;
				if (((previousValue != value) 
							|| (this._PRODUCT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PRODUCT.Entity = null;
						previousValue.ORDER_DETAILs.Remove(this);
					}
					this._PRODUCT.Entity = value;
					if ((value != null))
					{
						value.ORDER_DETAILs.Add(this);
						this._ID_PRO = value.ID_PRO;
					}
					else
					{
						this._ID_PRO = default(int);
					}
					this.SendPropertyChanged("PRODUCT");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ORDER_ORDER_DETAIL", Storage="_ORDER", ThisKey="ID_ORD", OtherKey="ID_ORD", IsForeignKey=true)]
		public ORDER ORDER
		{
			get
			{
				return this._ORDER.Entity;
			}
			set
			{
				ORDER previousValue = this._ORDER.Entity;
				if (((previousValue != value) 
							|| (this._ORDER.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ORDER.Entity = null;
						previousValue.ORDER_DETAILs.Remove(this);
					}
					this._ORDER.Entity = value;
					if ((value != null))
					{
						value.ORDER_DETAILs.Add(this);
						this._ID_ORD = value.ID_ORD;
					}
					else
					{
						this._ID_ORD = default(int);
					}
					this.SendPropertyChanged("ORDER");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CATEGORIES")]
	public partial class CATEGORy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_CAT;
		
		private string _NAME;
		
		private EntitySet<PRODUCT> _PRODUCTs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CATChanging(int value);
    partial void OnID_CATChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    #endregion
		
		public CATEGORy()
		{
			this._PRODUCTs = new EntitySet<PRODUCT>(new Action<PRODUCT>(this.attach_PRODUCTs), new Action<PRODUCT>(this.detach_PRODUCTs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CAT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_CAT
		{
			get
			{
				return this._ID_CAT;
			}
			set
			{
				if ((this._ID_CAT != value))
				{
					this.OnID_CATChanging(value);
					this.SendPropertyChanging();
					this._ID_CAT = value;
					this.SendPropertyChanged("ID_CAT");
					this.OnID_CATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CATEGORy_PRODUCT", Storage="_PRODUCTs", ThisKey="ID_CAT", OtherKey="ID_CAT")]
		public EntitySet<PRODUCT> PRODUCTs
		{
			get
			{
				return this._PRODUCTs;
			}
			set
			{
				this._PRODUCTs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PRODUCTs(PRODUCT entity)
		{
			this.SendPropertyChanging();
			entity.CATEGORy = this;
		}
		
		private void detach_PRODUCTs(PRODUCT entity)
		{
			this.SendPropertyChanging();
			entity.CATEGORy = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ADMIN")]
	public partial class ADMIN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UN;
		
		private string _PW;
		
		private string _NAME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUNChanging(string value);
    partial void OnUNChanged();
    partial void OnPWChanging(string value);
    partial void OnPWChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    #endregion
		
		public ADMIN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UN", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UN
		{
			get
			{
				return this._UN;
			}
			set
			{
				if ((this._UN != value))
				{
					this.OnUNChanging(value);
					this.SendPropertyChanging();
					this._UN = value;
					this.SendPropertyChanged("UN");
					this.OnUNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PW", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string PW
		{
			get
			{
				return this._PW;
			}
			set
			{
				if ((this._PW != value))
				{
					this.OnPWChanging(value);
					this.SendPropertyChanging();
					this._PW = value;
					this.SendPropertyChanged("PW");
					this.OnPWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(100)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ORDERS")]
	public partial class ORDER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_ORD;
		
		private System.Nullable<bool> _PAYMENT;
		
		private System.Nullable<bool> _STTSHIP;
		
		private System.Nullable<System.DateTime> _DATEORDER;
		
		private System.Nullable<System.DateTime> _DATESHIP;
		
		private System.Nullable<int> _ID_CUS;
		
		private EntitySet<ORDER_DETAIL> _ORDER_DETAILs;
		
		private EntityRef<CUSTOMER> _CUSTOMER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ORDChanging(int value);
    partial void OnID_ORDChanged();
    partial void OnPAYMENTChanging(System.Nullable<bool> value);
    partial void OnPAYMENTChanged();
    partial void OnSTTSHIPChanging(System.Nullable<bool> value);
    partial void OnSTTSHIPChanged();
    partial void OnDATEORDERChanging(System.Nullable<System.DateTime> value);
    partial void OnDATEORDERChanged();
    partial void OnDATESHIPChanging(System.Nullable<System.DateTime> value);
    partial void OnDATESHIPChanged();
    partial void OnID_CUSChanging(System.Nullable<int> value);
    partial void OnID_CUSChanged();
    #endregion
		
		public ORDER()
		{
			this._ORDER_DETAILs = new EntitySet<ORDER_DETAIL>(new Action<ORDER_DETAIL>(this.attach_ORDER_DETAILs), new Action<ORDER_DETAIL>(this.detach_ORDER_DETAILs));
			this._CUSTOMER = default(EntityRef<CUSTOMER>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ORD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_ORD
		{
			get
			{
				return this._ID_ORD;
			}
			set
			{
				if ((this._ID_ORD != value))
				{
					this.OnID_ORDChanging(value);
					this.SendPropertyChanging();
					this._ID_ORD = value;
					this.SendPropertyChanged("ID_ORD");
					this.OnID_ORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAYMENT", DbType="Bit")]
		public System.Nullable<bool> PAYMENT
		{
			get
			{
				return this._PAYMENT;
			}
			set
			{
				if ((this._PAYMENT != value))
				{
					this.OnPAYMENTChanging(value);
					this.SendPropertyChanging();
					this._PAYMENT = value;
					this.SendPropertyChanged("PAYMENT");
					this.OnPAYMENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STTSHIP", DbType="Bit")]
		public System.Nullable<bool> STTSHIP
		{
			get
			{
				return this._STTSHIP;
			}
			set
			{
				if ((this._STTSHIP != value))
				{
					this.OnSTTSHIPChanging(value);
					this.SendPropertyChanging();
					this._STTSHIP = value;
					this.SendPropertyChanged("STTSHIP");
					this.OnSTTSHIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATEORDER", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATEORDER
		{
			get
			{
				return this._DATEORDER;
			}
			set
			{
				if ((this._DATEORDER != value))
				{
					this.OnDATEORDERChanging(value);
					this.SendPropertyChanging();
					this._DATEORDER = value;
					this.SendPropertyChanged("DATEORDER");
					this.OnDATEORDERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATESHIP", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATESHIP
		{
			get
			{
				return this._DATESHIP;
			}
			set
			{
				if ((this._DATESHIP != value))
				{
					this.OnDATESHIPChanging(value);
					this.SendPropertyChanging();
					this._DATESHIP = value;
					this.SendPropertyChanged("DATESHIP");
					this.OnDATESHIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CUS", DbType="Int")]
		public System.Nullable<int> ID_CUS
		{
			get
			{
				return this._ID_CUS;
			}
			set
			{
				if ((this._ID_CUS != value))
				{
					if (this._CUSTOMER.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_CUSChanging(value);
					this.SendPropertyChanging();
					this._ID_CUS = value;
					this.SendPropertyChanged("ID_CUS");
					this.OnID_CUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ORDER_ORDER_DETAIL", Storage="_ORDER_DETAILs", ThisKey="ID_ORD", OtherKey="ID_ORD")]
		public EntitySet<ORDER_DETAIL> ORDER_DETAILs
		{
			get
			{
				return this._ORDER_DETAILs;
			}
			set
			{
				this._ORDER_DETAILs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CUSTOMER_ORDER", Storage="_CUSTOMER", ThisKey="ID_CUS", OtherKey="ID_CUS", IsForeignKey=true)]
		public CUSTOMER CUSTOMER
		{
			get
			{
				return this._CUSTOMER.Entity;
			}
			set
			{
				CUSTOMER previousValue = this._CUSTOMER.Entity;
				if (((previousValue != value) 
							|| (this._CUSTOMER.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CUSTOMER.Entity = null;
						previousValue.ORDERs.Remove(this);
					}
					this._CUSTOMER.Entity = value;
					if ((value != null))
					{
						value.ORDERs.Add(this);
						this._ID_CUS = value.ID_CUS;
					}
					else
					{
						this._ID_CUS = default(Nullable<int>);
					}
					this.SendPropertyChanged("CUSTOMER");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ORDER_DETAILs(ORDER_DETAIL entity)
		{
			this.SendPropertyChanging();
			entity.ORDER = this;
		}
		
		private void detach_ORDER_DETAILs(ORDER_DETAIL entity)
		{
			this.SendPropertyChanging();
			entity.ORDER = null;
		}
	}
}
#pragma warning restore 1591
